In [1]:
import torch
import torchaudio
import matplotlib.pyplot as plt
import os
from fonctions import *
from sklearn.preprocessing import normalize

In [5]:
# waveform, sample_rate = torchaudio.load("../Data/meme_taille_TEST/sig_1_10.WAV")
# spec_br, f_br, t_br, im_br = plt.specgram(waveform[0].t().numpy(), Fs = sample_rate, NFFT = 512, scale_by_freq = False, mode = 'magnitude', cmap = 'gray', scale='dB')
# spec_br, f_br, t_br, im_br = plt.specgram(waveform[0].t().numpy(), Fs = sample_rate, NFFT = 512, scale_by_freq = False, mode = 'psd', cmap = 'gray', scale='dB')

In [4]:

# spec_db = 10*np.log10(spec_br)
# # img = normalize(spec_db, norm='l2')
# plt.imshow(spec_db, cmap='gray', aspect='auto', origin='lower')
# spec_db
# np.min(spec_db)
# np.max(spec_db)
# img
# plt.pcolormesh(t_br, f_br, spec_db, cmap='gray')

In [1]:
from fonctions import *

######################### MEME TAILLE DE SIGNAUX

### Il faut d'abord créer le dossier meme_taille_TRAIN_1

# taille_sig("../Data/speech_TRAIN_1/TIMIT_TRAIN_1/DR1")
# taille_sig("../Data/speech_TRAIN_1/TIMIT_TRAIN_1/DR2")
# taille_sig("../Data/speech_TRAIN_1/TIMIT_TRAIN_1/DR3")
# taille_sig("../Data/speech_TRAIN_1/TIMIT_TRAIN_1/DR4")


### Il faut d'abord créer le dossier meme_taille_TRAIN_2

# taille_sig("../Data/speech_TRAIN_2/TIMIT_TRAIN_2/DR5")
# taille_sig("../Data/speech_TRAIN_2/TIMIT_TRAIN_2/DR6")
# taille_sig("../Data/speech_TRAIN_2/TIMIT_TRAIN_2/DR7")
# taille_sig("../Data/speech_TRAIN_2/TIMIT_TRAIN_2/DR8")


# taille_sig("../Data/speech_TEST/TIMIT_TEST/DR1")
# taille_sig("../Data/speech_TEST/TIMIT_TEST/DR2")
# taille_sig("../Data/speech_TEST/TIMIT_TEST/DR3")
# taille_sig("../Data/speech_TEST/TIMIT_TEST/DR4")
# taille_sig("../Data/speech_TEST/TIMIT_TEST/DR5")
# taille_sig("../Data/speech_TEST/TIMIT_TEST/DR6")
# taille_sig("../Data/speech_TEST/TIMIT_TEST/DR7")
# taille_sig("../Data/speech_TEST/TIMIT_TEST/DR8")

In [3]:
####################### SIGNAUX NON BRUITÉS

# for subdir, dirs, files in os.walk("../Data/meme_taille_TEST"):
#     for file in files:
#             subpath = os.path.join(subdir, file)
#             waveform, sample_rate = torchaudio.load(subpath)
#             spec, f, t, im = plt.specgram(waveform[0].t().numpy(), Fs = sample_rate, NFFT = 512, scale_by_freq = True, mode = 'psd', cmap = 'gray')
            
#             #on ajoute le spectro au dossier
             
#             path_list = subpath.split("/")
#             br_name = 'nb_' + path_list[3][:-3] + 'npy'

#             np.save('../Data/sig/non_bruité/' + br_name, spec.astype(np.float32))

            
######################## BRUITAGE DES SIGNAUX

# RSB = input('entrer le RSB voulu')
# bruit, sample_rate_bruit = torchaudio.load("../Data/babble.wav")
# bruit_rs = torchaudio.transforms.Resample(sample_rate_bruit, 16000)(bruit)
# for subdir, dirs, files in os.walk("../Data/meme_taille_TRAIN"):
#     for file in files:
#         if ('.WAV' in file):
#             subpath = os.path.join(subdir, file)
#             save_bruit(subpath, bruit, bruit_rs, RSB)
   

In [44]:
import os
import numpy as np

dataset_path = "../Data/Spec_TEST_SNR_5/Noisy/"
i=0
list_norm = np.ndarray((1,3))
print(list_norm)
# Compute the norm of the modulus spectrogram
for subdir, dirs, files in os.walk(dataset_path):
    for file in files:
        if ('mod' in file):
            subpath = os.path.join(subdir, file)
#             print(subpath, file)
            spec = np.load(subpath)
            norm = np.max(spec) - np.min(spec)
            spec_db = 20*np.log10(spec/norm)
            norm_db = np.max(spec_db) - np.min(spec_db)
            list_norm = np.append(list_norm, [[i, norm, norm_db]], axis=0)
            i+=1
np.save(dataset_path + "list_spec_norm.npy", list_norm.astype(np.float32))

[[1.72500000e+03 1.34301865e-02 1.16850365e+02]]


In [29]:
# list_norm = np.load(dataset_path+"Noisylist_spec_norm.npy")
print(list_norm)
np.shape(list_norm)
list_norm[1]

[[4.72500000e+03 5.94142079e-02 1.21754272e+02]
 [0.00000000e+00 1.95891224e-02 1.25798424e+02]
 [1.00000000e+00 2.25216392e-02 1.20307243e+02]
 ...
 [4.72300000e+03 2.99428739e-02 1.24949059e+02]
 [4.72400000e+03 4.08700593e-02 1.25738182e+02]
 [4.72500000e+03 5.94142079e-02 1.21754272e+02]]


array([0.00000000e+00, 1.95891224e-02, 1.25798424e+02])

In [43]:
filename = "n_sig_1_0_mod.npy"
spec = np.load(dataset_path+"Modulus/Data/"+filename)
spec_db=-20*np.log10(spec/list_norm[1][1])/list_norm[1][2]
print(spec_db)

[[0.55476797 0.41013914 0.32171702 ... 0.5129604  0.42601466 0.2949809 ]
 [0.3910214  0.48807684 0.3718132  ... 0.45932534 0.38871694 0.3404663 ]
 [0.43843675 0.50416005 0.4323509  ... 0.46255192 0.4573531  0.48955622]
 ...
 [0.68997747 0.72417617 0.68307227 ... 0.4476844  0.5921465  0.6256158 ]
 [0.67373127 0.82700855 0.7160547  ... 0.45603585 0.5707016  0.6354817 ]
 [0.678759   0.80146503 0.673226   ... 0.45452484 0.54818386 0.63006467]]
